// Banco de preguntas de incorporación — 30 preguntas por vacante
export type AnswerType = 'text' | 'yesno';

export interface Question {
  id: string;
  text: string;
  type: AnswerType;
}

// Preguntas generales (aplican a todos los puestos) — 10 preguntas
const PREGUNTAS_GENERALES: Question[] = [
  { id: 'g1', text: '¿Conoce el nombre y la actividad principal de la empresa donde trabajará?', type: 'yesno' },
  { id: 'g2', text: '¿Conoce las funciones del puesto para el cual fue seleccionado?', type: 'yesno' },
  { id: 'g3', text: '¿Conoce su horario de trabajo y días de descanso?', type: 'yesno' },
  { id: 'g4', text: '¿Conoce el lugar o sucursal donde debe presentarse a laborar?', type: 'yesno' },
  { id: 'g5', text: '¿Conoce el salario y la forma de pago acordados?', type: 'yesno' },
  { id: 'g6', text: '¿Conoce a su supervisor o persona responsable directa?', type: 'yesno' },
  { id: 'g7', text: '¿Conoce el uniforme o vestimenta requerida para su puesto?', type: 'yesno' },
  { id: 'g8', text: '¿Tiene conocimiento del reglamento interno de la empresa?', type: 'yesno' },
  { id: 'g9', text: '¿Conoce los procedimientos de seguridad y salud ocupacional?', type: 'yesno' },
  { id: 'g10', text: '¿Tiene alguna observación o consulta sobre el proceso de incorporación?', type: 'text' },
];

// Preguntas específicas por vacante — 20 preguntas
const PREGUNTAS_POR_VACANTE: Record<string, Question[]> = {
  'Auxiliar Contable': [
    { id: 'ac1', text: '¿Tiene experiencia en registro de facturas y comprobantes?', type: 'text' },
    { id: 'ac2', text: '¿Conoce el manejo de conciliaciones bancarias?', type: 'yesno' },
    { id: 'ac3', text: '¿Tiene experiencia en liquidación de planilla y cargas sociales?', type: 'text' },
    { id: 'ac4', text: '¿Conoce el sistema Hacienda DINAP y la declaración de impuestos?', type: 'yesno' },
    { id: 'ac5', text: '¿Tiene dominio de Excel nivel intermedio o avanzado?', type: 'text' },
    { id: 'ac6', text: '¿Conoce el manejo de proveedores y cuentas por pagar?', type: 'yesno' },
    { id: 'ac7', text: '¿Tiene experiencia con cuentas por cobrar y cobros a clientes?', type: 'text' },
    { id: 'ac8', text: '¿Conoce el manejo de caja chica y reembolsos?', type: 'yesno' },
    { id: 'ac9', text: '¿Tiene experiencia en preparación de informes financieros mensuales?', type: 'text' },
    { id: 'ac10', text: '¿Conoce el proceso de cierre contable mensual y anual?', type: 'yesno' },
    { id: 'ac11', text: '¿Tiene experiencia con sistemas ERP contables (SAP, QuickBooks, etc.)?', type: 'text' },
    { id: 'ac12', text: '¿Conoce el manejo de retenciones de impuestos (renta, IVA)?', type: 'yesno' },
    { id: 'ac13', text: '¿Tiene experiencia en auditoría interna o apoyo a auditorías externas?', type: 'text' },
    { id: 'ac14', text: '¿Conoce el proceso de depreciación de activos fijos?', type: 'yesno' },
    { id: 'ac15', text: '¿Tiene experiencia en control de inventarios desde el área contable?', type: 'text' },
    { id: 'ac16', text: '¿Conoce las obligaciones patronales ante la CCSS?', type: 'yesno' },
    { id: 'ac17', text: '¿Tiene experiencia en archivo y digitalización de documentos contables?', type: 'text' },
    { id: 'ac18', text: '¿Conoce la normativa del Código de Trabajo relacionada con prestaciones?', type: 'yesno' },
    { id: 'ac19', text: '¿Tiene experiencia elaborando presupuestos y proyecciones financieras?', type: 'text' },
    { id: 'ac20', text: '¿Posee algún título técnico o universitario en contaduría o afín?', type: 'yesno' },
  ],
  'Servicio al Cliente': [
    { id: 'sc1', text: '¿Tiene experiencia previa en atención al cliente?', type: 'text' },
    { id: 'sc2', text: '¿Conoce técnicas de comunicación asertiva con clientes?', type: 'yesno' },
    { id: 'sc3', text: '¿Tiene experiencia en manejo de quejas y reclamos?', type: 'text' },
    { id: 'sc4', text: '¿Conoce el uso de sistemas CRM o gestión de tickets?', type: 'yesno' },
    { id: 'sc5', text: '¿Tiene facilidad para trabajar bajo presión y metas de atención?', type: 'text' },
    { id: 'sc6', text: '¿Maneja protocolos de atención telefónica y por correo electrónico?', type: 'text' },
    { id: 'sc7', text: '¿Tiene experiencia en ventas cruzadas o sugerir productos al cliente?', type: 'text' },
    { id: 'sc8', text: '¿Conoce indicadores de calidad en servicio (NPS, CSAT, etc.)?', type: 'yesno' },
    { id: 'sc9', text: '¿Tiene experiencia atendiendo clientes en inglés?', type: 'text' },
    { id: 'sc10', text: '¿Conoce el procedimiento para escalar casos a otros departamentos?', type: 'yesno' },
    { id: 'sc11', text: '¿Tiene experiencia en atención presencial y manejo de filas?', type: 'text' },
    { id: 'sc12', text: '¿Conoce técnicas de manejo de clientes difíciles o molestos?', type: 'yesno' },
    { id: 'sc13', text: '¿Tiene experiencia en seguimiento post-venta o fidelización?', type: 'text' },
    { id: 'sc14', text: '¿Conoce el uso de WhatsApp Business o chat en vivo?', type: 'yesno' },
    { id: 'sc15', text: '¿Tiene experiencia en encuestas de satisfacción al cliente?', type: 'text' },
    { id: 'sc16', text: '¿Conoce el portafolio de productos o servicios de la empresa?', type: 'yesno' },
    { id: 'sc17', text: '¿Tiene experiencia con políticas de devoluciones y cambios?', type: 'text' },
    { id: 'sc18', text: '¿Maneja técnicas de escucha activa y empatía con el cliente?', type: 'text' },
    { id: 'sc19', text: '¿Tiene disponibilidad para rotar turnos incluyendo fines de semana?', type: 'yesno' },
    { id: 'sc20', text: '¿Posee capacitación en servicio al cliente o atención al usuario?', type: 'yesno' },
  ],
  'Asistente Administrativo': [
    { id: 'aa1', text: '¿Tiene experiencia en agenda y coordinación de reuniones?', type: 'text' },
    { id: 'aa2', text: '¿Conoce el manejo de correspondencia y redacción de oficios?', type: 'yesno' },
    { id: 'aa3', text: '¿Tiene dominio de paquete Office (Word, Excel, PowerPoint)?', type: 'text' },
    { id: 'aa4', text: '¿Conoce procedimientos de archivo y control documental?', type: 'yesno' },
    { id: 'aa5', text: '¿Tiene experiencia en control de suministros de oficina?', type: 'text' },
    { id: 'aa6', text: '¿Conoce el manejo de cuentas por pagar y notas de entrega?', type: 'yesno' },
    { id: 'aa7', text: '¿Tiene experiencia coordinando proveedores y servicios externos?', type: 'text' },
    { id: 'aa8', text: '¿Conoce el uso de plataformas de firma electrónica y documentos digitales?', type: 'yesno' },
    { id: 'aa9', text: '¿Tiene experiencia apoyando en procesos de compra?', type: 'text' },
    { id: 'aa10', text: '¿Conoce procedimientos de control de acceso y seguridad de la oficina?', type: 'yesno' },
    { id: 'aa11', text: '¿Tiene experiencia elaborando informes y presentaciones ejecutivas?', type: 'text' },
    { id: 'aa12', text: '¿Conoce el manejo de presupuestos de gastos administrativos?', type: 'yesno' },
    { id: 'aa13', text: '¿Tiene experiencia en atención a visitantes y clientes en recepción?', type: 'text' },
    { id: 'aa14', text: '¿Conoce el uso de herramientas de videoconferencia (Zoom, Teams)?', type: 'yesno' },
    { id: 'aa15', text: '¿Tiene experiencia en gestión de viajes y reservaciones corporativas?', type: 'text' },
    { id: 'aa16', text: '¿Conoce procesos de inducción y bienvenida a personal nuevo?', type: 'yesno' },
    { id: 'aa17', text: '¿Tiene experiencia en manejo de bases de datos administrativas?', type: 'text' },
    { id: 'aa18', text: '¿Conoce normas de confidencialidad y protección de datos personales?', type: 'yesno' },
    { id: 'aa19', text: '¿Tiene experiencia apoyando en la elaboración de organigramas y procedimientos?', type: 'text' },
    { id: 'aa20', text: '¿Posee estudios técnicos o universitarios en administración o afín?', type: 'yesno' },
  ],
  'Cajero': [
    { id: 'cj1', text: '¿Tiene experiencia en manejo de caja y arqueo diario?', type: 'text' },
    { id: 'cj2', text: '¿Conoce el uso de terminales de punto de venta (POS)?', type: 'yesno' },
    { id: 'cj3', text: '¿Tiene experiencia en manejo de efectivo, tarjetas y pagos electrónicos?', type: 'text' },
    { id: 'cj4', text: '¿Conoce procedimientos de detección de billetes falsos?', type: 'yesno' },
    { id: 'cj5', text: '¿Tiene experiencia en devoluciones de dinero a clientes?', type: 'text' },
    { id: 'cj6', text: '¿Conoce el manejo de promociones, cupones y descuentos en caja?', type: 'yesno' },
    { id: 'cj7', text: '¿Tiene experiencia con sistemas de facturación electrónica?', type: 'text' },
    { id: 'cj8', text: '¿Conoce procedimientos de apertura y cierre de caja?', type: 'yesno' },
    { id: 'cj9', text: '¿Tiene experiencia en conciliación de vouchers tarjetarios al final del turno?', type: 'text' },
    { id: 'cj10', text: '¿Conoce el manejo de tarjetas de regalo y vales electrónicos?', type: 'yesno' },
    { id: 'cj11', text: '¿Tiene experiencia en control de fondo de caja y depósitos bancarios?', type: 'text' },
    { id: 'cj12', text: '¿Conoce protocolos de atención al cliente en caja?', type: 'yesno' },
    { id: 'cj13', text: '¿Tiene experiencia en manejo de divisas o moneda extranjera?', type: 'text' },
    { id: 'cj14', text: '¿Conoce procedimientos ante discrepancias en el arqueo de caja?', type: 'yesno' },
    { id: 'cj15', text: '¿Tiene experiencia en reembolso de productos y emisión de notas de crédito?', type: 'text' },
    { id: 'cj16', text: '¿Conoce el uso de lectores de código de barras y balanzas en punto de venta?', type: 'yesno' },
    { id: 'cj17', text: '¿Tiene experiencia en cierre fiscal mensual de POS?', type: 'text' },
    { id: 'cj18', text: '¿Conoce protocolos de seguridad para prevención de fraude en caja?', type: 'yesno' },
    { id: 'cj19', text: '¿Tiene disponibilidad para rotar turnos incluyendo fines de semana?', type: 'yesno' },
    { id: 'cj20', text: '¿Posee experiencia en cajero de supermercado, farmacia o tienda por departamento?', type: 'yesno' },
  ],
  'Recursos Humanos': [
    { id: 'rh1', text: '¿Tiene experiencia en reclutamiento y selección de personal?', type: 'text' },
    { id: 'rh2', text: '¿Conoce el proceso de planilla y cálculo de cargas sociales en Costa Rica?', type: 'yesno' },
    { id: 'rh3', text: '¿Tiene experiencia en elaboración de contratos laborales?', type: 'text' },
    { id: 'rh4', text: '¿Conoce la normativa del Código de Trabajo de Costa Rica?', type: 'yesno' },
    { id: 'rh5', text: '¿Tiene experiencia en procesos de inducción y capacitación de personal?', type: 'text' },
    { id: 'rh6', text: '¿Conoce el manejo de expedientes digitales y físicos de empleados?', type: 'yesno' },
    { id: 'rh7', text: '¿Tiene experiencia en evaluaciones de desempeño?', type: 'text' },
    { id: 'rh8', text: '¿Conoce el proceso de registro y reporte a la CCSS (ASEMED-ASEPROLA)?', type: 'yesno' },
    { id: 'rh9', text: '¿Tiene experiencia en gestión de ausencias, permisos y vacaciones?', type: 'text' },
    { id: 'rh10', text: '¿Conoce las obligaciones patronales (FCL, Banco Popular, INS)?', type: 'yesno' },
    { id: 'rh11', text: '¿Tiene experiencia en manejo de conflictos laborales y mediación?', type: 'text' },
    { id: 'rh12', text: '¿Conoce políticas de prevención de acoso laboral y discriminación?', type: 'yesno' },
    { id: 'rh13', text: '¿Tiene experiencia en programas de bienestar y clima organizacional?', type: 'text' },
    { id: 'rh14', text: '¿Conoce el proceso de despido, preaviso y cesantía?', type: 'yesno' },
    { id: 'rh15', text: '¿Tiene experiencia en nómina y control de horas extras?', type: 'text' },
    { id: 'rh16', text: '¿Conoce el uso de sistemas de gestión de RRHH (BambooHR, Workday, etc.)?', type: 'yesno' },
    { id: 'rh17', text: '¿Tiene experiencia en seguridad y salud ocupacional desde RRHH?', type: 'text' },
    { id: 'rh18', text: '¿Conoce procedimientos de auditoría laboral y compliance?', type: 'yesno' },
    { id: 'rh19', text: '¿Tiene experiencia en comunicación interna y boletines corporativos?', type: 'text' },
    { id: 'rh20', text: '¿Posee título universitario en administración, psicología o RRHH?', type: 'yesno' },
  ],
  'Bodega': [
    { id: 'bg1', text: '¿Tiene experiencia en control de inventarios y stock?', type: 'text' },
    { id: 'bg2', text: '¿Conoce el uso de sistemas WMS (Warehouse Management System)?', type: 'yesno' },
    { id: 'bg3', text: '¿Tiene experiencia en recepción y despacho de mercancía?', type: 'text' },
    { id: 'bg4', text: '¿Conoce procedimientos de conteo cíclico e inventarios físicos?', type: 'yesno' },
    { id: 'bg5', text: '¿Tiene experiencia con montacargas y equipos de elevación?', type: 'text' },
    { id: 'bg6', text: '¿Conoce el uso de pistolas de código de barras y colectores de datos?', type: 'yesno' },
    { id: 'bg7', text: '¿Tiene experiencia en picking, packing y embalaje de productos?', type: 'text' },
    { id: 'bg8', text: '¿Conoce normas de almacenamiento seguro (FIFO, FEFO, LIFO)?', type: 'yesno' },
    { id: 'bg9', text: '¿Tiene experiencia en control de mermas y productos dañados?', type: 'text' },
    { id: 'bg10', text: '¿Conoce el manejo de devoluciones a proveedores desde bodega?', type: 'yesno' },
    { id: 'bg11', text: '¿Tiene experiencia en carga y descarga de contenedores?', type: 'text' },
    { id: 'bg12', text: '¿Conoce procedimientos de rotulación y señalización de áreas?', type: 'yesno' },
    { id: 'bg13', text: '¿Tiene experiencia en despacho de rutas y preparación de pedidos?', type: 'text' },
    { id: 'bg14', text: '¿Conoce el uso de tarimas, estibas y medidas de almacenamiento?', type: 'yesno' },
    { id: 'bg15', text: '¿Tiene experiencia en control de temperaturas para productos perecederos?', type: 'text' },
    { id: 'bg16', text: '¿Conoce protocolos de seguridad con EPP en bodega (casco, guantes)?', type: 'yesno' },
    { id: 'bg17', text: '¿Tiene experiencia en reportes de inventario y diferencias de stock?', type: 'text' },
    { id: 'bg18', text: '¿Conoce el manejo de productos peligrosos o químicos en bodega?', type: 'yesno' },
    { id: 'bg19', text: '¿Tiene disponibilidad para trabajar en turnos rotativos?', type: 'yesno' },
    { id: 'bg20', text: '¿Posee certificación en operación de montacargas o equipos de bodega?', type: 'yesno' },
  ],
  'Conductor': [
    { id: 'cd1', text: '¿Posee licencia de conducir vigente (B1, B2, B3 o C1 según corresponda)?', type: 'yesno' },
    { id: 'cd2', text: '¿Tiene experiencia en conducción de vehículos de carga o distribución?', type: 'text' },
    { id: 'cd3', text: '¿Conoce las rutas principales del Gran Área Metropolitana y provincia?', type: 'yesno' },
    { id: 'cd4', text: '¿Tiene experiencia en uso de GPS y aplicaciones de navegación?', type: 'text' },
    { id: 'cd5', text: '¿Conoce el procedimiento de revisión técnica diaria del vehículo?', type: 'yesno' },
    { id: 'cd6', text: '¿Tiene experiencia en control de bitácora de viaje y reporte de novedades?', type: 'text' },
    { id: 'cd7', text: '¿Conoce las normativas de tránsito y límites de velocidad de Costa Rica?', type: 'yesno' },
    { id: 'cd8', text: '¿Tiene experiencia en manejo de manifiestos de carga y guías de despacho?', type: 'text' },
    { id: 'cd9', text: '¿Conoce procedimientos de carga y descarga de mercancía segura?', type: 'yesno' },
    { id: 'cd10', text: '¿Tiene experiencia en entregas con acuse de recibo y firma del cliente?', type: 'text' },
    { id: 'cd11', text: '¿Conoce el manejo de vehículos con sistema de tracción en rutas difíciles?', type: 'yesno' },
    { id: 'cd12', text: '¿Tiene experiencia conduciendo en horarios nocturnos o fines de semana?', type: 'text' },
    { id: 'cd13', text: '¿Conoce protocolos de seguridad vial y uso de cinturón y EPP?', type: 'yesno' },
    { id: 'cd14', text: '¿Tiene experiencia en mantenimiento preventivo básico del vehículo?', type: 'text' },
    { id: 'cd15', text: '¿Conoce procedimientos en caso de accidente de tránsito o avería?', type: 'yesno' },
    { id: 'cd16', text: '¿Tiene experiencia con vehículos refrigerados para productos perecederos?', type: 'text' },
    { id: 'cd17', text: '¿Conoce el manejo de pagos en ruta y cobros a clientes (si aplica)?', type: 'yesno' },
    { id: 'cd18', text: '¿Tiene experiencia en reporte de consumo de combustible y rendimiento?', type: 'text' },
    { id: 'cd19', text: '¿Posee curso de conducción segura o defensive driving?', type: 'yesno' },
    { id: 'cd20', text: '¿Tiene disponibilidad para viajes largos dentro o fuera del país?', type: 'yesno' },
  ],
  'Asesor de Ventas': [
    { id: 'av1', text: '¿Tiene experiencia previa en ventas de automóviles o vehículos?', type: 'text' },
    { id: 'av2', text: '¿Conoce técnicas de prospección y cierre de ventas?', type: 'yesno' },
    { id: 'av3', text: '¿Tiene experiencia con CRM y gestión de pipeline comercial?', type: 'text' },
    { id: 'av4', text: '¿Conoce el portafolio de marcas y modelos que distribuye la empresa?', type: 'yesno' },
    { id: 'av5', text: '¿Tiene experiencia en financiamiento vehicular y trámite de crédito?', type: 'text' },
    { id: 'av6', text: '¿Conoce los procedimientos de transferencia de vehículos y trámites COFINS?', type: 'yesno' },
    { id: 'av7', text: '¿Tiene experiencia en venta de accesorios y servicios complementarios?', type: 'text' },
    { id: 'av8', text: '¿Conoce indicadores de gestión comercial (conversión, ticket promedio)?', type: 'yesno' },
    { id: 'av9', text: '¿Tiene experiencia en seguimiento post-venta y satisfacción del cliente?', type: 'text' },
    { id: 'av10', text: '¿Conoce el proceso de prueba de manejo y protocolos de seguridad?', type: 'yesno' },
    { id: 'av11', text: '¿Tiene experiencia en manejo de objeciones y negociación de precios?', type: 'text' },
    { id: 'av12', text: '¿Conoce el uso de redes sociales para prospección de clientes?', type: 'yesno' },
    { id: 'av13', text: '¿Tiene experiencia en atención a clientes corporativos o flotas?', type: 'text' },
    { id: 'av14', text: '¿Conoce las garantías de fabrica y extendidas de los vehículos?', type: 'yesno' },
    { id: 'av15', text: '¿Tiene experiencia en actualización de inventario y disponibilidad de unidades?', type: 'text' },
    { id: 'av16', text: '¿Conoce procedimientos de entrega de vehículo al cliente (delivery process)?', type: 'yesno' },
    { id: 'av17', text: '¿Tiene experiencia en campañas promocionales y eventos de venta?', type: 'text' },
    { id: 'av18', text: '¿Conoce la normativa de protección al consumidor en Costa Rica?', type: 'yesno' },
    { id: 'av19', text: '¿Tiene disponibilidad para trabajar sábados y domingos?', type: 'yesno' },
    { id: 'av20', text: '¿Posee capacitación en técnicas de venta o marketing?', type: 'yesno' },
  ],
  'Técnico Automotriz': [
    { id: 'ta1', text: '¿Posee formación técnica en mecánica automotriz?', type: 'yesno' },
    { id: 'ta2', text: '¿Tiene experiencia en diagnóstico de fallas con equipos OBD2?', type: 'text' },
    { id: 'ta3', text: '¿Conoce sistemas eléctricos y electrónicos de vehículos modernos?', type: 'yesno' },
    { id: 'ta4', text: '¿Tiene experiencia en mantenimiento preventivo (aceite, filtros, frenos)?', type: 'text' },
    { id: 'ta5', text: '¿Conoce el manejo de manuales técnicos y diagramas de fabricante?', type: 'yesno' },
    { id: 'ta6', text: '¿Tiene experiencia en sistemas de inyección electrónica y turboalimentación?', type: 'text' },
    { id: 'ta7', text: '¿Conoce protocolos de seguridad en el taller (EPP, elevadores)?', type: 'yesno' },
    { id: 'ta8', text: '¿Tiene experiencia en reparación de transmisiones automáticas y manuales?', type: 'text' },
    { id: 'ta9', text: '¿Conoce sistemas híbridos y eléctricos vehiculares?', type: 'yesno' },
    { id: 'ta10', text: '¿Tiene experiencia en alineación, balanceo y suspensión?', type: 'text' },
    { id: 'ta11', text: '¿Conoce el manejo de orden de reparación y reporte de tiempos?', type: 'yesno' },
    { id: 'ta12', text: '¿Tiene experiencia en sistemas de climatización vehicular (A/C)?', type: 'text' },
    { id: 'ta13', text: '¿Conoce el proceso de garantía de fabricante y reclamos técnicos?', type: 'yesno' },
    { id: 'ta14', text: '¿Tiene experiencia en soldadura y trabajos de latonería básica?', type: 'text' },
    { id: 'ta15', text: '¿Conoce el uso de equipos especializados (alineador 3D, escáner, etc.)?', type: 'yesno' },
    { id: 'ta16', text: '¿Tiene experiencia en control de calidad de reparaciones?', type: 'text' },
    { id: 'ta17', text: '¿Conoce procedimientos de disposición de residuos peligrosos (aceites, baterías)?', type: 'yesno' },
    { id: 'ta18', text: '¿Tiene experiencia en capacitación continua con marcas específicas?', type: 'text' },
    { id: 'ta19', text: '¿Posee certificaciones técnicas de fabricantes reconocidos?', type: 'yesno' },
    { id: 'ta20', text: '¿Tiene disponibilidad para turnos rotativos y guardias?', type: 'yesno' },
  ],
  'Repuestos': [
    { id: 'rp1', text: '¿Tiene experiencia en venta de repuestos automotrices?', type: 'text' },
    { id: 'rp2', text: '¿Conoce sistemas de catalogación de repuestos por VIN o número de parte?', type: 'yesno' },
    { id: 'rp3', text: '¿Tiene experiencia en control de inventario de repuestos?', type: 'text' },
    { id: 'rp4', text: '¿Conoce el uso de sistemas de gestión de taller y repuestos?', type: 'yesno' },
    { id: 'rp5', text: '¿Tiene experiencia en despacho de pedidos y manejo de backorder?', type: 'text' },
    { id: 'rp6', text: '¿Conoce procedimientos de importación de repuestos y trámites aduanales?', type: 'yesno' },
    { id: 'rp7', text: '¿Tiene experiencia en atención a mecánicos y talleres externos?', type: 'text' },
    { id: 'rp8', text: '¿Conoce el manejo de garantías de repuestos y devoluciones?', type: 'yesno' },
    { id: 'rp9', text: '¿Tiene experiencia en identificación de partes equivalentes y alternativas?', type: 'text' },
    { id: 'rp10', text: '¿Conoce el proceso de compra de repuestos a proveedores nacionales e internacionales?', type: 'yesno' },
    { id: 'rp11', text: '¿Tiene experiencia en control de stock mínimo y reposición automática?', type: 'text' },
    { id: 'rp12', text: '¿Conoce el manejo de repuestos críticos y de alta rotación?', type: 'yesno' },
    { id: 'rp13', text: '¿Tiene experiencia en facturación electrónica de repuestos?', type: 'text' },
    { id: 'rp14', text: '¿Conoce procedimientos de organización física del almacén de repuestos?', type: 'yesno' },
    { id: 'rp15', text: '¿Tiene experiencia en reportes de ventas y márgenes de repuestos?', type: 'text' },
    { id: 'rp16', text: '¿Conoce el manejo de descuentos corporativos y precios especiales?', type: 'yesno' },
    { id: 'rp17', text: '¿Tiene experiencia en atención al cliente en mostrador de repuestos?', type: 'text' },
    { id: 'rp18', text: '¿Conoce procedimientos de control de mermas y repuestos obsoletos?', type: 'yesno' },
    { id: 'rp19', text: '¿Tiene disponibilidad para trabajar sábados?', type: 'yesno' },
    { id: 'rp20', text: '¿Posee formación técnica automotriz o experiencia en tiendas de repuestos?', type: 'yesno' },
  ],
  'Inspector Vehicular': [
    { id: 'iv1', text: '¿Conoce los lineamientos de la revisión técnica vehicular de Costa Rica?', type: 'yesno' },
    { id: 'iv2', text: '¿Tiene experiencia en inspección de sistemas de frenos, suspensión y dirección?', type: 'text' },
    { id: 'iv3', text: '¿Conoce los parámetros de emisiones de gases y opacidad?', type: 'yesno' },
    { id: 'iv4', text: '¿Tiene experiencia en inspección de sistemas de iluminación y señalización?', type: 'text' },
    { id: 'iv5', text: '¿Conoce el uso de equipos de medición para inspección (frenómetro, opacímetro)?', type: 'yesno' },
    { id: 'iv6', text: '¿Tiene experiencia en revisión de neumáticos y estado de la banda de rodamiento?', type: 'text' },
    { id: 'iv7', text: '¿Conoce los requisitos de seguridad activiva y pasiva del vehículo?', type: 'yesno' },
    { id: 'iv8', text: '¿Tiene experiencia en emisión de certificados y actas de inspección?', type: 'text' },
    { id: 'iv9', text: '¿Conoce el proceso de reinspección y plazos legales?', type: 'yesno' },
    { id: 'iv10', text: '¿Tiene experiencia en atención al cliente durante el proceso de inspección?', type: 'text' },
    { id: 'iv11', text: '¿Conoce el manejo de no conformidades y observaciones técnicas?', type: 'yesno' },
    { id: 'iv12', text: '¿Tiene experiencia en inspección de vehículos de carga y transporte público?', type: 'text' },
    { id: 'iv13', text: '¿Conoce la normativa del MOPT y Consejo de Transporte Público?', type: 'yesno' },
    { id: 'iv14', text: '¿Tiene experiencia en reportes diarios de inspección y estadísticas?', type: 'text' },
    { id: 'iv15', text: '¿Conoce protocolos de bioseguridad e higiene en estaciones de inspección?', type: 'yesno' },
    { id: 'iv16', text: '¿Tiene experiencia en uso de plataformas digitales de registro de inspección?', type: 'text' },
    { id: 'iv17', text: '¿Conoce los límites legales de emisiones según tipo de combustible?', type: 'yesno' },
    { id: 'iv18', text: '¿Tiene experiencia en inspección visual y estructural del vehículo?', type: 'text' },
    { id: 'iv19', text: '¿Posee formación técnica mecánica o certificación en inspección vehicular?', type: 'yesno' },
    { id: 'iv20', text: '¿Tiene disponibilidad para trabajo en estaciones móviles y rotación de sedes?', type: 'yesno' },
  ],
  'Operario de Producción': [
    { id: 'op1', text: '¿Tiene experiencia en líneas de producción de alimentos o bebidas?', type: 'text' },
    { id: 'op2', text: '¿Conoce las normas de inocuidad alimentaria (HACCP, BPM, ISO 22000)?', type: 'yesno' },
    { id: 'op3', text: '¿Tiene experiencia en operación de maquinaria industrial?', type: 'text' },
    { id: 'op4', text: '¿Conoce protocolos de higiene personal en planta de alimentos?', type: 'yesno' },
    { id: 'op5', text: '¿Tiene experiencia en control de calidad en línea de producción?', type: 'text' },
    { id: 'op6', text: '¿Conoce el uso de equipos de protección personal en ambiente industrial?', type: 'yesno' },
    { id: 'op7', text: '¿Tiene experiencia en empaque, etiquetado y codificación de productos?', type: 'text' },
    { id: 'op8', text: '¿Conoce procedimientos de limpieza y sanitización de equipos?', type: 'yesno' },
    { id: 'op9', text: '¿Tiene experiencia en manejo de materias primas y control de lotes?', type: 'text' },
    { id: 'op10', text: '¿Conoce el proceso de pasteurización o tratamiento térmico (si aplica)?', type: 'yesno' },
    { id: 'op11', text: '¿Tiene experiencia en reporte de producción y rendimiento por turno?', type: 'text' },
    { id: 'op12', text: '¿Conoce protocolos de respuesta a emergencias en planta industrial?', type: 'yesno' },
    { id: 'op13', text: '¿Tiene experiencia en manejo de residuos industriales y reciclaje?', type: 'text' },
    { id: 'op14', text: '¿Conoce el uso de sistemas SCADA o paneles de control de producción?', type: 'yesno' },
    { id: 'op15', text: '¿Tiene experiencia en cambio de formato y preparación de línea (setup)?', type: 'text' },
    { id: 'op16', text: '¿Conoce procedimientos de mantenimiento básico de máquinas?', type: 'yesno' },
    { id: 'op17', text: '¿Tiene experiencia en trabajo por metas y indicadores de productividad?', type: 'text' },
    { id: 'op18', text: '¿Conoce el manejo de productos no conformes y desviaciones de proceso?', type: 'yesno' },
    { id: 'op19', text: '¿Tiene disponibilidad para trabajo en turnos rotativos incluyendo nocturno?', type: 'yesno' },
    { id: 'op20', text: '¿Posee formación técnica industrial o experiencia en planta de producción?', type: 'yesno' },
  ],
  'Auxiliar de Bodega': [
    { id: 'ab1', text: '¿Tiene experiencia en recepción y verificación de mercancía?', type: 'text' },
    { id: 'ab2', text: '¿Conoce el uso de sistemas de inventario y colectores de datos?', type: 'yesno' },
    { id: 'ab3', text: '¿Tiene experiencia en picking y packing de pedidos?', type: 'text' },
    { id: 'ab4', text: '¿Conoce el manejo de tarimas y estibas?', type: 'yesno' },
    { id: 'ab5', text: '¿Tiene experiencia en control de stock y conteos cíclicos?', type: 'text' },
    { id: 'ab6', text: '¿Conoce el uso de pistolas lectoras de código de barras?', type: 'yesno' },
    { id: 'ab7', text: '¿Tiene experiencia en despacho de rutas y preparación de pedidos?', type: 'text' },
    { id: 'ab8', text: '¿Conoce protocolos de seguridad con EPP en bodega?', type: 'yesno' },
    { id: 'ab9', text: '¿Tiene experiencia en control de mermas y productos dañados?', type: 'text' },
    { id: 'ab10', text: '¿Conoce el manejo de FIFO y control de fechas de vencimiento?', type: 'yesno' },
    { id: 'ab11', text: '¿Tiene experiencia en carga y descarga manual de mercancía?', type: 'text' },
    { id: 'ab12', text: '¿Conoce el proceso de devoluciones y notas de crédito?', type: 'yesno' },
    { id: 'ab13', text: '¿Tiene experiencia en organización y rotulación de estantes?', type: 'text' },
    { id: 'ab14', text: '¿Conoce procedimientos de manejo de productos refrigerados o congelados?', type: 'yesno' },
    { id: 'ab15', text: '¿Tiene experiencia en reportes de inventario y diferencias de stock?', type: 'text' },
    { id: 'ab16', text: '¿Conoce el manejo de documentación de entrada y salida de mercancía?', type: 'yesno' },
    { id: 'ab17', text: '¿Tiene experiencia con montacargas manuales o eléctricos?', type: 'text' },
    { id: 'ab18', text: '¿Conoce medidas de ergonomía para levantamiento de cargas?', type: 'yesno' },
    { id: 'ab19', text: '¿Tiene disponibilidad para turnos rotativos?', type: 'yesno' },
    { id: 'ab20', text: '¿Posee experiencia en bodega de supermercado, distribuidora o industria?', type: 'yesno' },
  ],
  'Logística': [
    { id: 'lg1', text: '¿Tiene experiencia en planificación de rutas de distribución?', type: 'text' },
    { id: 'lg2', text: '¿Conoce el uso de sistemas de gestión de transporte (TMS)?', type: 'yesno' },
    { id: 'lg3', text: '¿Tiene experiencia en coordinación de flotas vehiculares?', type: 'text' },
    { id: 'lg4', text: '¿Conoce procedimientos de cadena de suministro (supply chain)?', type: 'yesno' },
    { id: 'lg5', text: '¿Tiene experiencia en control de costos logísticos y fletes?', type: 'text' },
    { id: 'lg6', text: '¿Conoce el manejo de proveedores de transporte y negociación de tarifas?', type: 'yesno' },
    { id: 'lg7', text: '¿Tiene experiencia en seguimiento de entregas y GPS de flotillas?', type: 'text' },
    { id: 'lg8', text: '¿Conoce procedimientos de importación y exportación de mercancía?', type: 'yesno' },
    { id: 'lg9', text: '¿Tiene experiencia en gestión de bodegas y centros de distribución?', type: 'text' },
    { id: 'lg10', text: '¿Conoce el proceso de aduana y trámites de comercio exterior?', type: 'yesno' },
    { id: 'lg11', text: '¿Tiene experiencia en optimización de cargas y aprovechamiento de vehicles?', type: 'text' },
    { id: 'lg12', text: '¿Conoce indicadores logísticos (OTIF, lead time, costo por entrega)?', type: 'yesno' },
    { id: 'lg13', text: '¿Tiene experiencia en manejo de devoluciones logísticas (reverse logistics)?', type: 'text' },
    { id: 'lg14', text: '¿Conoce el uso de WMS y control de inventario en tránsito?', type: 'yesno' },
    { id: 'lg15', text: '¿Tiene experiencia en reportes de cumplimiento de rutas y entregas?', type: 'text' },
    { id: 'lg16', text: '¿Conoce la normativa de transporte de mercancía peligrosa?', type: 'yesno' },
    { id: 'lg17', text: '¿Tiene experiencia en coordinación con tercerizadores de logística (3PL)?', type: 'text' },
    { id: 'lg18', text: '¿Conoce el manejo de seguros de carga y reclamos por daños?', type: 'yesno' },
    { id: 'lg19', text: '¿Tiene experiencia en planificación de demanda y forecast?', type: 'text' },
    { id: 'lg20', text: '¿Posee formación técnica o universitaria en logística o cadena de suministro?', type: 'yesno' },
  ],
  'Control de Calidad': [
    { id: 'cc1', text: '¿Tiene experiencia en control de calidad de productos alimenticios?', type: 'text' },
    { id: 'cc2', text: '¿Conoce las normas ISO 9001 e ISO 22000?', type: 'yesno' },
    { id: 'cc3', text: '¿Tiene experiencia en muestreo y análisis de laboratorio?', type: 'text' },
    { id: 'cc4', text: '¿Conoce los principios HACCP y Buenas Prácticas de Manufactura (BPM)?', type: 'yesno' },
    { id: 'cc5', text: '¿Tiene experiencia en inspección visual y dimensional de productos?', type: 'text' },
    { id: 'cc6', text: '¿Conoce el uso de instrumentos de medición (balanzas, calibradores, pH)?', type: 'yesno' },
    { id: 'cc7', text: '¿Tiene experiencia en manejo de no conformidades y acciones correctivas?', type: 'text' },
    { id: 'cc8', text: '¿Conoce el proceso de auditorías internas de calidad?', type: 'yesno' },
    { id: 'cc9', text: '¿Tiene experiencia en elaboración de reportes e indicadores de calidad?', type: 'text' },
    { id: 'cc10', text: '¿Conoce los estándares de inocuidad alimentaria de Costa Rica?', type: 'yesno' },
    { id: 'cc11', text: '¿Tiene experiencia en control de proveedores y evaluación de materias primas?', type: 'text' },
    { id: 'cc12', text: '¿Conoce el manejo de desviaciones de proceso y CAPA?', type: 'yesno' },
    { id: 'cc13', text: '¿Tiene experiencia en calibración de equipos de medición?', type: 'text' },
    { id: 'cc14', text: '¿Conoce el proceso de trazabilidad de lotes y retiro de producto (recall)?', type: 'yesno' },
    { id: 'cc15', text: '¿Tiene experiencia en validación de procesos productivos?', type: 'text' },
    { id: 'cc16', text: '¿Conoce la normativa del Servicio Nacional de Calidad (Senasa)?', type: 'yesno' },
    { id: 'cc17', text: '¿Tiene experiencia en capacitación al personal en normas de calidad?', type: 'text' },
    { id: 'cc18', text: '¿Conoce el uso de software de gestión de calidad (QMS)?', type: 'yesno' },
    { id: 'cc19', text: '¿Tiene experiencia en mejoramiento continuo (Kaizen, 5S, Six Sigma)?', type: 'text' },
    { id: 'cc20', text: '¿Posee formación técnica o universitaria en calidad o ingeniería de alimentos?', type: 'yesno' },
  ],
  'Ventas': [
    { id: 'vt1', text: '¿Tiene experiencia previa en ventas de productos de consumo?', type: 'text' },
    { id: 'vt2', text: '¿Conoce técnicas de prospección y cierre de ventas?', type: 'yesno' },
    { id: 'vt3', text: '¿Tiene experiencia con CRM y gestión de cartera de clientes?', type: 'text' },
    { id: 'vt4', text: '¿Conoce el portafolio de productos de la empresa?', type: 'yesno' },
    { id: 'vt5', text: '¿Tiene experiencia en ventas B2B y B2C?', type: 'text' },
    { id: 'vt6', text: '¿Conoce indicadores comerciales (conversión, ticket promedio, recurrencia)?', type: 'yesno' },
    { id: 'vt7', text: '¿Tiene experiencia en negociación de precios y condiciones comerciales?', type: 'text' },
    { id: 'vt8', text: '¿Conoce el proceso de merchandising y exhibición de productos?', type: 'yesno' },
    { id: 'vt9', text: '¿Tiene experiencia en campañas promocionales y lanzamientos?', type: 'text' },
    { id: 'vt10', text: '¿Conoce el uso de redes sociales como canal de ventas?', type: 'yesno' },
    { id: 'vt11', text: '¿Tiene experiencia en manejo de objeciones y cierre consultivo?', type: 'text' },
    { id: 'vt12', text: '¿Conoce procedimientos de facturación y cobros?', type: 'yesno' },
    { id: 'vt13', text: '¿Tiene experiencia en seguimiento post-venta y fidelización?', type: 'text' },
    { id: 'vt14', text: '¿Conoce el manejo de metas y comisiones?', type: 'yesno' },
    { id: 'vt15', text: '¿Tiene experiencia en trabajo por ruta o visita a clientes?', type: 'text' },
    { id: 'vt16', text: '¿Conoce la normativa de protección al consumidor en Costa Rica?', type: 'yesno' },
    { id: 'vt17', text: '¿Tiene experiencia en presentaciones comerciales y demostraciones de producto?', type: 'text' },
    { id: 'vt18', text: '¿Conoce el uso de plataformas de e-commerce?', type: 'yesno' },
    { id: 'vt19', text: '¿Tiene disponibilidad para trabajar fines de semana y feriados?', type: 'yesno' },
    { id: 'vt20', text: '¿Posee formación en ventas, mercadeo o administración?', type: 'yesno' },
  ],
  'Auxiliar de Tienda': [
    { id: 'at1', text: '¿Tiene experiencia en reposición de productos en estantes?', type: 'text' },
    { id: 'at2', text: '¿Conoce procedimientos de rotación de productos (FIFO, control de fechas)?', type: 'yesno' },
    { id: 'at3', text: '¿Tiene experiencia en atención al cliente en piso de venta?', type: 'text' },
    { id: 'at4', text: '¿Conoce el uso de pistolas lectoras de código de barras?', type: 'yesno' },
    { id: 'at5', text: '¿Tiene experiencia en cambio de precios y rotulación de productos?', type: 'text' },
    { id: 'at6', text: '¿Conoce el manejo de planogramas y exhibición de mercancía?', type: 'yesno' },
    { id: 'at7', text: '¿Tiene experiencia en control de inventario y conteos cíclicos?', type: 'text' },
    { id: 'at8', text: '¿Conoce procedimientos de prevención de pérdidas y mermas?', type: 'yesno' },
    { id: 'at9', text: '¿Tiene experiencia en organización de bodega de tienda?', type: 'text' },
    { id: 'at10', text: '¿Conoce el manejo de productos perecederos y control de temperatura?', type: 'yesno' },
    { id: 'at11', text: '¿Tiene experiencia en recepción de mercancía y control de entregas?', type: 'text' },
    { id: 'at12', text: '¿Conoce el uso de balanzas y etiquetadoras en área de frescos?', type: 'yesno' },
    { id: 'at13', text: '¿Tiene experiencia en apoyo a caja en horas pico?', type: 'text' },
    { id: 'at14', text: '¿Conoce protocolos de higiene y limpieza del área de venta?', type: 'yesno' },
    { id: 'at15', text: '¿Tiene experiencia en manejo de devoluciones y cambios de producto?', type: 'text' },
    { id: 'at16', text: '¿Conoce el uso de montacargas manuales en tienda?', type: 'yesno' },
    { id: 'at17', text: '¿Tiene experiencia en reporte de faltantes y reposición urgente?', type: 'text' },
    { id: 'at18', text: '¿Conoce el manejo de productos promocionales y exhibiciones especiales?', type: 'yesno' },
    { id: 'at19', text: '¿Tiene disponibilidad para turnos rotativos incluyendo fines de semana?', type: 'yesno' },
    { id: 'at20', text: '¿Posee experiencia en supermercado, tienda por departamento o minimarket?', type: 'yesno' },
  ],
  'Supervisor': [
    { id: 'sp1', text: '¿Tiene experiencia supervisando equipos de trabajo?', type: 'text' },
    { id: 'sp2', text: '¿Conoce técnicas de liderazgo y gestión de personal operativo?', type: 'yesno' },
    { id: 'sp3', text: '¿Tiene experiencia en control de indicadores de gestión (KPIs)?', type: 'text' },
    { id: 'sp4', text: '¿Conoce procedimientos de apertura y cierre de tienda o sucursal?', type: 'yesno' },
    { id: 'sp5', text: '¿Tiene experiencia en manejo de conflictos y mediación entre personal?', type: 'text' },
    { id: 'sp6', text: '¿Conoce el proceso de programación de turnos y horarios?', type: 'yesno' },
    { id: 'sp7', text: '¿Tiene experiencia en control de inventario y mermas?', type: 'text' },
    { id: 'sp8', text: '¿Conoce el uso de reportes de ventas y análisis de desempeño?', type: 'yesno' },
    { id: 'sp9', text: '¿Tiene experiencia en capacitación e inducción de personal nuevo?', type: 'text' },
    { id: 'sp10', text: '¿Conoce protocolos de seguridad y salud ocupacional del área?', type: 'yesno' },
    { id: 'sp11', text: '¿Tiene experiencia en atención de quejas de clientes escaladas?', type: 'text' },
    { id: 'sp12', text: '¿Conoce procedimientos de control de caja y arqueos?', type: 'yesno' },
    { id: 'sp13', text: '¿Tiene experiencia en evaluaciones de desempeño del personal a cargo?', type: 'text' },
    { id: 'sp14', text: '¿Conoce el uso de sistemas POS y reportes de gestión?', type: 'yesno' },
    { id: 'sp15', text: '¿Tiene experiencia en manejo de presupuesto operativo de la sucursal?', type: 'text' },
    { id: 'sp16', text: '¿Conoce el proceso de auditoría interna y cumplimiento de procedimientos?', type: 'yesno' },
    { id: 'sp17', text: '¿Tiene experiencia en coordinación con otros departamentos (RRHH, logística)?', type: 'text' },
    { id: 'sp18', text: '¿Conoce el manejo de emergencias y protocolos de evacuación?', type: 'yesno' },
    { id: 'sp19', text: '¿Tiene disponibilidad para rotar entre sucursales?', type: 'yesno' },
    { id: 'sp20', text: '¿Posee formación técnica o universitaria en administración o afín?', type: 'yesno' },
  ],
  'Ejecutivo Bancario': [
    { id: 'eb1', text: '¿Tiene experiencia en atención al cliente en entidad financiera?', type: 'text' },
    { id: 'eb2', text: '¿Conoce los productos y servicios bancarios (cuentas, tarjetas, créditos)?', type: 'yesno' },
    { id: 'eb3', text: '¿Tiene experiencia en apertura y cierre de cuentas bancarias?', type: 'text' },
    { id: 'eb4', text: '¿Conoce el proceso de colocación de créditos y análisis de capacidad de pago?', type: 'yesno' },
    { id: 'eb5', text: '¿Tiene experiencia en venta cruzada de productos financieros?', type: 'text' },
    { id: 'eb6', text: '¿Conoce la normativa de prevención de lavado de dinero (PLD)?', type: 'yesno' },
    { id: 'eb7', text: '¿Tiene experiencia con sistemas bancarios core y plataformas digitales?', type: 'text' },
    { id: 'eb8', text: '¿Conoce procedimientos KYC (Know Your Customer) y debida diligencia?', type: 'yesno' },
    { id: 'eb9', text: '¿Tiene experiencia en manejo de quejas y reclamos de clientes bancarios?', type: 'text' },
    { id: 'eb10', text: '¿Conoce los requisitos de firma electrónica y bancarización digital?', type: 'yesno' },
    { id: 'eb11', text: '¿Tiene experiencia en captación de clientes y metas comerciales?', type: 'text' },
    { id: 'eb12', text: '¿Conoce el proceso de tarjetas de crédito y débito (emisión, reposición)?', type: 'yesno' },
    { id: 'eb13', text: '¿Tiene experiencia en manejo de divisas y transferencias internacionales?', type: 'text' },
    { id: 'eb14', text: '¿Conoce las normas de secreto y confidencialidad bancaria?', type: 'yesno' },
    { id: 'eb15', text: '¿Tiene experiencia en seguros asociados a productos bancarios?', type: 'text' },
    { id: 'eb16', text: '¿Conoce procedimientos de detección de fraudes y transacciones sospechosas?', type: 'yesno' },
    { id: 'eb17', text: '¿Tiene experiencia en banca de personas y banca de empresas?', type: 'text' },
    { id: 'eb18', text: '¿Conoce el uso de banca en línea y app móvil del banco?', type: 'yesno' },
    { id: 'eb19', text: '¿Tiene disponibilidad para rotar entre agencias?', type: 'yesno' },
    { id: 'eb20', text: '¿Posee título universitario en administración, economía o finanzas?', type: 'yesno' },
  ],
  'Ejecutivo de Ventas': [
    { id: 'ev1', text: '¿Tiene experiencia en ventas de productos farmacéuticos o médicos?', type: 'text' },
    { id: 'ev2', text: '¿Conoce técnicas de venta consultiva en sector salud?', type: 'yesno' },
    { id: 'ev3', text: '¿Tiene experiencia en gestión de cartera de clientes institucionales?', type: 'text' },
    { id: 'ev4', text: '¿Conoce el portafolio de productos de la empresa?', type: 'yesno' },
    { id: 'ev5', text: '¿Tiene experiencia con CRM y reportes de gestión comercial?', type: 'text' },
    { id: 'ev6', text: '¿Conoce el proceso de licitaciones en el sector salud (CCSS, clínicas)?', type: 'yesno' },
    { id: 'ev7', text: '¿Tiene experiencia en presentaciones técnicas a profesionales de la salud?', type: 'text' },
    { id: 'ev8', text: '¿Conoce el manejo de muestras médicas y material promocional?', type: 'yesno' },
    { id: 'ev9', text: '¿Tiene experiencia en metas de venta y comisiones?', type: 'text' },
    { id: 'ev10', text: '¿Conoce la normativa de publicidad de productos sanitarios?', type: 'yesno' },
    { id: 'ev11', text: '¿Tiene experiencia en seguimiento post-venta y soporte al cliente?', type: 'text' },
    { id: 'ev12', text: '¿Conoce el uso de plataformas digitales para gestión comercial?', type: 'yesno' },
    { id: 'ev13', text: '¿Tiene experiencia en territorio nacional y disponibilidad para viajar?', type: 'text' },
    { id: 'ev14', text: '¿Conoce el proceso de importación de equipos médicos (si aplica)?', type: 'yesno' },
    { id: 'ev15', text: '¿Tiene experiencia en manejo de objeciones técnicas y científicas?', type: 'text' },
    { id: 'ev16', text: '¿Conoce el ciclo de compra institucional (hospitales, clínicas, farmacias)?', type: 'yesno' },
    { id: 'ev17', text: '¿Tiene experiencia en reportes de mercado y competencia?', type: 'text' },
    { id: 'ev18', text: '¿Conoce indicadores comerciales (conversión, recurrencia, ticket promedio)?', type: 'yesno' },
    { id: 'ev19', text: '¿Tiene experiencia en inglés conversacional para clientes internacionales?', type: 'text' },
    { id: 'ev20', text: '¿Posee formación en ventas, mercadeo o áreas de la salud?', type: 'yesno' },
  ],
  'Analista Financiero': [
    { id: 'af1', text: '¿Tiene experiencia en análisis de estados financieros?', type: 'text' },
    { id: 'af2', text: '¿Conoce modelos de valuación y proyecciones financieras?', type: 'yesno' },
    { id: 'af3', text: '¿Tiene experiencia en análisis de riesgo crediticio?', type: 'text' },
    { id: 'af4', text: '¿Conoce indicadores financieros (ratios, ROE, ROA, EBITDA)?', type: 'yesno' },
    { id: 'af5', text: '¿Tiene experiencia en Excel avanzado (tablas dinámicas, macros, Power Query)?', type: 'text' },
    { id: 'af6', text: '¿Conoce el uso de herramientas BI (Power BI, Tableau)?', type: 'yesno' },
    { id: 'af7', text: '¿Tiene experiencia en presupuesto y forecast corporativo?', type: 'text' },
    { id: 'af8', text: '¿Conoce la normativa contable vigente (NIIF/IFRS)?', type: 'yesno' },
    { id: 'af9', text: '¿Tiene experiencia en análisis de varianzas y control presupuestal?', type: 'text' },
    { id: 'af10', text: '¿Conoce el proceso de cierre financiero mensual y anual?', type: 'yesno' },
    { id: 'af11', text: '¿Tiene experiencia en análisis de inversiones y valor presente neto (VPN)?', type: 'text' },
    { id: 'af12', text: '¿Conoce el manejo de tesorería y flujos de caja?', type: 'yesno' },
    { id: 'af13', text: '¿Tiene experiencia en reportes a alta gerencia y presentaciones ejecutivas?', type: 'text' },
    { id: 'af14', text: '¿Conoce el mercado de valores costarricense y regulación CONASSIF?', type: 'yesno' },
    { id: 'af15', text: '¿Tiene experiencia en análisis de sensibilidad y escenarios?', type: 'text' },
    { id: 'af16', text: '¿Conoce el manejo de indicadores macroeconómicos (inflación, tipo de cambio)?', type: 'yesno' },
    { id: 'af17', text: '¿Tiene experiencia en sistemas ERP financieros (SAP, Oracle)?', type: 'text' },
    { id: 'af18', text: '¿Conoce procedimientos de auditoría interna financiera?', type: 'yesno' },
    { id: 'af19', text: '¿Tiene experiencia en manejo de base de datos financieros (SQL, Access)?', type: 'text' },
    { id: 'af20', text: '¿Posee título universitario en finanzas, economía o contaduría?', type: 'yesno' },
  ],
  'Operaciones': [
    { id: 'op1', text: '¿Tiene experiencia en gestión de operaciones bancarias o administrativas?', type: 'text' },
    { id: 'op2', text: '¿Conoce procedimientos de compensación y liquidación de transacciones?', type: 'yesno' },
    { id: 'op3', text: '¿Tiene experiencia en control y conciliación de cuentas operativas?', type: 'text' },
    { id: 'op4', text: '¿Conoce el proceso de clearing y cámaras de compensación?', type: 'yesno' },
    { id: 'op5', text: '¿Tiene experiencia en manejo de efectivo y custodia de valores?', type: 'text' },
    { id: 'op6', text: '¿Conoce protocolos de seguridad operacional y continuidad de negocio?', type: 'yesno' },
    { id: 'op7', text: '¿Tiene experiencia en reportes regulatorios a SUGEF?', type: 'text' },
    { id: 'op8', text: '¿Conoce el manejo de proveedores operativos y contratos de servicio?', type: 'yesno' },
    { id: 'op9', text: '¿Tiene experiencia en optimización de procesos (Lean, Six Sigma)?', type: 'text' },
    { id: 'op10', text: '¿Conoce el uso de sistemas de gestión documental y workflow?', type: 'yesno' },
    { id: 'op11', text: '¿Tiene experiencia en control de indicadores de calidad operativa?', type: 'text' },
    { id: 'op12', text: '¿Conoce procedimientos de archivo y retención documental legal?', type: 'yesno' },
    { id: 'op13', text: '¿Tiene experiencia en atención de incidencias y mesas de ayuda internas?', type: 'text' },
    { id: 'op14', text: '¿Conoce el proceso de digitalización y automatización de procesos?', type: 'yesno' },
    { id: 'op15', text: '¿Tiene experiencia en gestión de riesgos operacionales?', type: 'text' },
    { id: 'op16', text: '¿Conoce normativas de compliance y prevención de lavado de activos?', type: 'yesno' },
    { id: 'op17', text: '¿Tiene experiencia en coordinación entre sucursales y oficinas centrales?', type: 'text' },
    { id: 'op18', text: '¿Conoce el uso de herramientas de proyecto (Microsoft Project, Jira)?', type: 'yesno' },
    { id: 'op19', text: '¿Tiene disponibilidad para guardias y atención de emergencias operativas?', type: 'yesno' },
    { id: 'op20', text: '¿Posee formación técnica o universitaria en administración o ingeniería?', type: 'yesno' },
  ],
  'Dependiente de Farmacia': [
    { id: 'df1', text: '¿Tiene experiencia en atención al cliente en farmacia o retail?', type: 'text' },
    { id: 'df2', text: '¿Conoce el manejo de productos farmacéuticos de venta libre?', type: 'yesno' },
    { id: 'df3', text: '¿Tiene experiencia en control de inventario y fechas de vencimiento?', type: 'text' },
    { id: 'df4', text: '¿Conoce el uso de sistemas POS y facturación electrónica en farmacia?', type: 'yesno' },
    { id: 'df5', text: '¿Tiene experiencia en manejo de productos refrigerados (vacunas, insulinas)?', type: 'text' },
    { id: 'df6', text: '¿Conoce procedimientos de control de productos controlados (recetas retiene)?', type: 'yesno' },
    { id: 'df7', text: '¿Tiene experiencia en venta de productos cosméticos y de higiene personal?', type: 'text' },
    { id: 'df8', text: '¿Conoce el manejo de promociones y combos en farmacia?', type: 'yesno' },
    { id: 'df9', text: '¿Tiene experiencia en arqueo de caja y control de efectivo?', type: 'text' },
    { id: 'df10', text: '¿Conoce el procedimiento de devoluciones y cambios de productos?', type: 'yesno' },
    { id: 'df11', text: '¿Tiene experiencia en reposición de estantes y control de existencias mínimas?', type: 'text' },
    { id: 'df12', text: '¿Conoce protocolos de higiene y manipulación de productos farmacéuticos?', type: 'yesno' },
    { id: 'df13', text: '¿Tiene experiencia en orientación básica al cliente sobre productos OTC?', type: 'text' },
    { id: 'df14', text: '¿Conoce el manejo de pedidos a proveedores y reposición de stock?', type: 'yesno' },
    { id: 'df15', text: '¿Tiene experiencia en reporte de mermas y productos vencidos?', type: 'text' },
    { id: 'df16', text: '¿Conoce el uso de balanzas y etiquetadoras (si aplica)?', type: 'yesno' },
    { id: 'df17', text: '¿Tiene experiencia en atención de recetas médicas y derivación al regente?', type: 'text' },
    { id: 'df18', text: '¿Conoce el procedimiento ante sospecha de recetas falsas o adulteradas?', type: 'yesno' },
    { id: 'df19', text: '¿Tiene disponibilidad para turnos rotativos incluyendo fines de semana?', type: 'yesno' },
    { id: 'df20', text: '¿Posee formación técnica en farmacia o experiencia comprobable en el área?', type: 'yesno' },
  ],
  'Regente Farmacéutico': [
    { id: 'rf1', text: '¿Posee título universitario en Farmacia y registro del Colegio de Farmacéuticos?', type: 'yesno' },
    { id: 'rf2', text: '¿Tiene experiencia como regente farmacéutico en establecimientos autorizados?', type: 'text' },
    { id: 'rf3', text: '¿Conoce la normativa del Ministerio de Salud para establecimientos farmacéuticos?', type: 'yesno' },
    { id: 'rf4', text: '¿Tiene experiencia en control y dispensación de medicamentos controlados?', type: 'text' },
    { id: 'rf5', text: '¿Conoce el procedimiento de recetas retiene y registro de medicamentos controlados?', type: 'yesno' },
    { id: 'rf6', text: '¿Tiene experiencia en validación de recetas médicas y dosificación?', type: 'text' },
    { id: 'rf7', text: '¿Conoce las Buenas Prácticas de Almacenamiento (BPA) de medicamentos?', type: 'yesno' },
    { id: 'rf8', text: '¿Tiene experiencia en control de cadena de frío para medicamentos termolábiles?', type: 'text' },
    { id: 'rf9', text: '¿Conoce el proceso de reporte de reacciones adversas (farmacovigilancia)?', type: 'yesno' },
    { id: 'rf10', text: '¿Tiene experiencia en auditoría interna del establecimiento farmacéutico?', type: 'text' },
    { id: 'rf11', text: '¿Conoce el manejo de medicamentos vencidos y su disposición final?', type: 'yesno' },
    { id: 'rf12', text: '¿Tiene experiencia en capacitación al personal auxiliar de farmacia?', type: 'text' },
    { id: 'rf13', text: '¿Conoce el registro sanitario de productos y su verificación?', type: 'yesno' },
    { id: 'rf14', text: '¿Tiene experiencia en atención y orientación farmacéutica al paciente?', type: 'text' },
    { id: 'rf15', text: '¿Conoce el procedimiento de quejas y reclamos relacionados con medicamentos?', type: 'yesno' },
    { id: 'rf16', text: '¿Tiene experiencia en manejo de inventario y control de existencias de medicamentos?', type: 'text' },
    { id: 'rf17', text: '¿Conoce la normativa de publicidad de productos farmacéuticos?', type: 'yesno' },
    { id: 'rf18', text: '¿Tiene experiencia en coordinación con proveedores y distribuidores farmacéuticos?', type: 'text' },
    { id: 'rf19', text: '¿Conoce el procedimiento de inspección del Ministerio de Salud?', type: 'yesno' },
    { id: 'rf20', text: '¿Posee cursos de actualización en farmacia clínica o atención farmacéutica?', type: 'yesno' },
  ],
  'Técnico': [
    { id: 'tc1', text: '¿Posee formación técnica en electromedicina o biomedicina?', type: 'yesno' },
    { id: 'tc2', text: '¿Tiene experiencia en mantenimiento preventivo y correctivo de equipos médicos?', type: 'text' },
    { id: 'tc3', text: '¿Conoce el uso de manuales de servicio de fabricantes de equipos médicos?', type: 'yesno' },
    { id: 'tc4', text: '¿Tiene experiencia en calibración de equipos de medición médica?', type: 'text' },
    { id: 'tc5', text: '¿Conoce protocolos de seguridad eléctrica en equipos biomédicos?', type: 'yesno' },
    { id: 'tc6', text: '¿Tiene experiencia en instalación y puesta en marcha de equipos médicos?', type: 'text' },
    { id: 'tc7', text: '¿Conoce el manejo de instrumentos de medición (multímetro, osciloscopio)?', type: 'yesno' },
    { id: 'tc8', text: '¿Tiene experiencia en diagnóstico de fallas electrónicas en equipos médicos?', type: 'text' },
    { id: 'tc9', text: '¿Conoce las normas de seguridad hospitalaria y manejo en áreas estériles?', type: 'yesno' },
    { id: 'tc10', text: '¿Tiene experiencia en reportes de servicio y órdenes de trabajo?', type: 'text' },
    { id: 'tc11', text: '¿Conoce el proceso de garantía de fabricante y repuestos originales?', type: 'yesno' },
    { id: 'tc12', text: '¿Tiene experiencia en capacitación al usuario final sobre uso de equipos?', type: 'text' },
    { id: 'tc13', text: '¿Conoce el manejo de software de equipos médicos y actualizaciones de firmware?', type: 'yesno' },
    { id: 'tc14', text: '¿Tiene experiencia en mantenimiento de equipos de imagenología (rayos X, ultrasonido)?', type: 'text' },
    { id: 'tc15', text: '¿Conoce protocolos de desinfección y esterilización de equipos médicos?', type: 'yesno' },
    { id: 'tc16', text: '¿Tiene experiencia en control de historial de mantenimiento por equipo?', type: 'text' },
    { id: 'tc17', text: '¿Conoce la normativa del Ministerio de Salud para equipos médicos?', type: 'yesno' },
    { id: 'tc18', text: '¿Tiene experiencia en manejo de piezas de repuesto e inventario técnico?', type: 'text' },
    { id: 'tc19', text: '¿Posee certificaciones técnicas de fabricantes de equipos médicos?', type: 'yesno' },
    { id: 'tc20', text: '¿Tiene disponibilidad para guardias y atención de emergencias técnicas?', type: 'yesno' },
  ],
  'Técnico Biomédico': [
    { id: 'tb1', text: '¿Posee título técnico o universitario en ingeniería biomédica o afín?', type: 'yesno' },
    { id: 'tb2', text: '¿Tiene experiencia en mantenimiento de equipos biomédicos en hospitales o clínicas?', type: 'text' },
    { id: 'tb3', text: '¿Conoce las normas IEC 60601 para seguridad de equipos electromédicos?', type: 'yesno' },
    { id: 'tb4', text: '¿Tiene experiencia en calibración y verificación de equipos de monitoreo vital?', type: 'text' },
    { id: 'tb5', text: '¿Conoce el proceso de gestión de riesgo de equipos médicos (ISO 14971)?', type: 'yesno' },
    { id: 'tb6', text: '¿Tiene experiencia en mantenimiento de ventiladores, monitores y bombas de infusión?', type: 'text' },
    { id: 'tb7', text: '¿Conoce protocolos de seguridad en quirófano y áreas críticas?', type: 'yesno' },
    { id: 'tb8', text: '¿Tiene experiencia en instalación y configuración de equipos de imagenología?', type: 'text' },
    { id: 'tb9', text: '¿Conoce el manejo de estándares de comunicación médica (HL7, DICOM)?', type: 'yesno' },
    { id: 'tb10', text: '¿Tiene experiencia en pruebas eléctricas de seguridad en equipos médicos?', type: 'text' },
    { id: 'tb11', text: '¿Conoce el proceso de inventario y gestión de parque de equipos biomédicos?', type: 'yesno' },
    { id: 'tb12', text: '¿Tiene experiencia en capacitación al personal médico sobre uso seguro de equipos?', type: 'text' },
    { id: 'tb13', text: '¿Conoce procedimientos de disposición final de equipos médicos obsoletos?', type: 'yesno' },
    { id: 'tb14', text: '¿Tiene experiencia en reportes de incidentes adversos relacionados con equipos?', type: 'text' },
    { id: 'tb15', text: '¿Conoce el proceso de validación de equipos médicos nuevos?', type: 'yesno' },
    { id: 'tb16', text: '¿Tiene experiencia en manejo de contratos de servicio con fabricantes?', type: 'text' },
    { id: 'tb17', text: '¿Conoce el uso de software de gestión de mantenimiento asistido por computadora (CMMS)?', type: 'yesno' },
    { id: 'tb18', text: '¿Tiene experiencia en mantenimiento de equipos de laboratorio clínico?', type: 'text' },
    { id: 'tb19', text: '¿Posee certificaciones de fabricantes (Philips, GE, Dräger, etc.)?', type: 'yesno' },
    { id: 'tb20', text: '¿Tiene disponibilidad para trabajo en campo en diferentes hospitales del país?', type: 'yesno' },
  ],
  'Soporte Técnico': [
    { id: 'st1', text: '¿Tiene experiencia en soporte técnico de hardware y software?', type: 'text' },
    { id: 'st2', text: '¿Conoce el uso de sistemas de tickets (Jira, Freshdesk, Zendesk)?', type: 'yesno' },
    { id: 'st3', text: '¿Tiene experiencia en configuración de redes y equipos de comunicación?', type: 'text' },
    { id: 'st4', text: '¿Conoce sistemas operativos Windows y Linux a nivel administrador?', type: 'yesno' },
    { id: 'st5', text: '¿Tiene experiencia en soporte remoto y herramientas (TeamViewer, AnyDesk)?', type: 'text' },
    { id: 'st6', text: '¿Conoce protocolos de diagnóstico y resolución de problemas (troubleshooting)?', type: 'yesno' },
    { id: 'st7', text: '¿Tiene experiencia en instalación y configuración de software corporativo?', type: 'text' },
    { id: 'st8', text: '¿Conoce el manejo de Active Directory y gestión de usuarios?', type: 'yesno' },
    { id: 'st9', text: '¿Tiene experiencia en respaldo y recuperación de datos (backup)?', type: 'text' },
    { id: 'st10', text: '¿Conoce protocolos de seguridad informática y antivirus corporativo?', type: 'yesno' },
    { id: 'st11', text: '¿Tiene experiencia en soporte a usuarios finales (mesa de ayuda)?', type: 'text' },
    { id: 'st12', text: '¿Conoce el uso de VPN y acceso remoto seguro?', type: 'yesno' },
    { id: 'st13', text: '¿Tiene experiencia en mantenimiento preventivo de computadoras y equipos?', type: 'text' },
    { id: 'st14', text: '¿Conoce el proceso de escalado de incidencias a nivel 2 y 3?', type: 'yesno' },
    { id: 'st15', text: '¿Tiene experiencia en manejo de impresoras y periféricos?', type: 'text' },
    { id: 'st16', text: '¿Conoce el uso de Office 365 y Google Workspace?', type: 'yesno' },
    { id: 'st17', text: '¿Tiene experiencia en documentación de procedimientos técnicos?', type: 'text' },
    { id: 'st18', text: '¿Conoce protocolos de confidencialidad y protección de datos?', type: 'yesno' },
    { id: 'st19', text: '¿Tiene disponibilidad para guardias y atención de emergencias técnicas?', type: 'yesno' },
    { id: 'st20', text: '¿Posee certificaciones técnicas (CompTIA, Microsoft, Cisco) o formación afín?', type: 'yesno' },
  ],
  'Operario': [
    { id: 'or1', text: '¿Tiene experiencia en construcción o fabricación de materiales?', type: 'text' },
    { id: 'or2', text: '¿Conoce el uso de herramientas manuales y eléctricas?', type: 'yesno' },
    { id: 'or3', text: '¿Tiene experiencia en operación de maquinaria industrial?', type: 'text' },
    { id: 'or4', text: '¿Conoce protocolos de seguridad en planta industrial (EPP)?', type: 'yesno' },
    { id: 'or5', text: '¿Tiene experiencia en control de calidad de producto terminado?', type: 'text' },
    { id: 'or6', text: '¿Conoce procedimientos de manejo de materias primas?', type: 'yesno' },
    { id: 'or7', text: '¿Tiene experiencia en empaque y embalaje de productos de construcción?', type: 'text' },
    { id: 'or8', text: '¿Conoce el manejo de equipos de elevación y transporte interno?', type: 'yesno' },
    { id: 'or9', text: '¿Tiene experiencia en mantenimiento básico de máquinas?', type: 'text' },
    { id: 'or10', text: '¿Conoce protocolos de respuesta a emergencias industriales?', type: 'yesno' },
    { id: 'or11', text: '¿Tiene experiencia en reporte de producción por turno?', type: 'text' },
    { id: 'or12', text: '¿Conoce procedimientos de limpieza y orden (5S) en planta?', type: 'yesno' },
    { id: 'or13', text: '¿Tiene experiencia en manejo de residuos industriales?', type: 'text' },
    { id: 'or14', text: '¿Conoce el proceso de secado, horneado o tratamiento térmico (si aplica)?', type: 'yesno' },
    { id: 'or15', text: '¿Tiene experiencia en trabajo por metas e indicadores de productividad?', type: 'text' },
    { id: 'or16', text: '¿Conoce el uso de carretillas y equipos de movimiento de materiales?', type: 'yesno' },
    { id: 'or17', text: '¿Tiene experiencia en control de inventario en planta de producción?', type: 'text' },
    { id: 'or18', text: '¿Conoce procedimientos de prevención de accidentes laborales?', type: 'yesno' },
    { id: 'or19', text: '¿Tiene disponibilidad para turnos rotativos incluyendo nocturno?', type: 'yesno' },
    { id: 'or20', text: '¿Posee formación técnica industrial o experiencia comprobable en planta?', type: 'yesno' },
  ],
};

// Preguntas genéricas para vacantes que no tienen banco específico (20 preguntas)
const PREGUNTAS_GENERICAS_ESPECIFICAS: Question[] = [
  { id: 'ge1', text: '¿Tiene experiencia previa en un puesto similar?', type: 'text' },
  { id: 'ge2', text: '¿Conoce las herramientas o equipos que utilizará en su puesto?', type: 'yesno' },
  { id: 'ge3', text: '¿Tiene experiencia trabajando en equipo?', type: 'text' },
  { id: 'ge4', text: '¿Conoce los procedimientos de seguridad específicos de su área?', type: 'yesno' },
  { id: 'ge5', text: '¿Tiene experiencia en atención al cliente?', type: 'text' },
  { id: 'ge6', text: '¿Conoce el uso de sistemas informáticos básicos?', type: 'yesno' },
  { id: 'ge7', text: '¿Tiene experiencia en manejo de inventarios o materiales?', type: 'text' },
  { id: 'ge8', text: '¿Conoce indicadores de gestión o productividad de su área?', type: 'yesno' },
  { id: 'ge9', text: '¿Tiene experiencia en reportes o documentación de procesos?', type: 'text' },
  { id: 'ge10', text: '¿Conoce las normativas de higiene y seguridad ocupacional?', type: 'yesno' },
  { id: 'ge11', text: '¿Tiene experiencia en trabajo bajo metas o indicadores?', type: 'text' },
  { id: 'ge12', text: '¿Conoce procedimientos de calidad de su área?', type: 'yesno' },
  { id: 'ge13', text: '¿Tiene experiencia en capacitación o inducción de personal nuevo?', type: 'text' },
  { id: 'ge14', text: '¿Conoce el manejo de equipos de protección personal (EPP)?', type: 'yesno' },
  { id: 'ge15', text: '¿Tiene experiencia en trabajo con maquinaria o herramientas especializadas?', type: 'text' },
  { id: 'ge16', text: '¿Conoce los procedimientos de emergencia y evacuación?', type: 'yesno' },
  { id: 'ge17', text: '¿Tiene experiencia en manejo de residuos o productos químicos (si aplica)?', type: 'text' },
  { id: 'ge18', text: '¿Conoce el reglamento interno de trabajo de la empresa?', type: 'yesno' },
  { id: 'ge19', text: '¿Tiene disponibilidad para horarios flexibles o rotativos?', type: 'yesno' },
  { id: 'ge20', text: '¿Posee formación técnica o experiencia comprobable relacionada al puesto?', type: 'yesno' },
];

// Obtiene las 30 preguntas para una vacante específica (10 generales + 20 específicas)
export function getQuestionsForVacancy(vacancyTitle: string): Question[] {
  const especificas = PREGUNTAS_POR_VACANTE[vacancyTitle] ?? PREGUNTAS_GENERICAS_ESPECIFICAS;
  return [...PREGUNTAS_GENERALES, ...especificas];
}
